spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recommendation_service_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: super_secret_key
  expiration: 3600000