server:
  tomcat:
    apr:
      enabled: false

logging:
  level:
    com:
      example:
        demo:
          service:
            ParserService: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recommendation_service_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true

  task:
    scheduling:
      pool:
        size: 5

parser:
  limit: 3
  maxDescription: 500
  fixedRateMain: 30000
  fixedRateRSS: 30000

management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: "*"
        exclude: shutdown

telegram:
  bot:
    name: ttestpython_bot
    token: 6481641133:AAFCJ3MNNtM0ZnygPFh3cmUpwSIUF3PzOvA

yandex:
  token: AQVN1qBjEZSo9U4XS2Nd3YquMBIpkWOgSqkgHCh2
  folder-id: b1ge5mgjepbtdo48h05j