server:
  tomcat:
    apr:
      enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recommendation_service_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update

  flyway:
    enabled: true
    baseline-on-migrate: true

  task:
    scheduling:
      pool:
        size: 5

parser:
  limit: 3
  maxDescription: 2000
  fixedRateMain: 600000
  fixedRateRSS: 600000

management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: "*"
        exclude: shutdown

telegram:
  bot:
    name: ttestpython_bot
    token: 6481641133:AAFCJ3MNNtM0ZnygPFh3cmUpwSIUF3PzOvA